name: Run Python Script and Commit CSV

on:
  push:
    branches:
      - main # 触发动作的分支
  schedule:
    # 每周1-5的UTC时间14:15运行，按需调整，即北京时间的22:15
    - cron: '15 14 * * 1-5'

jobs:
  build-and-commit-csv:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # 你的 Python 版本

    - name: Configure Git
      run: |
        git config --local user.email "oishi@qq.com"
        git config --local user.name "oishi"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pywencai
        pip install datetime
        pip install pandas openpyxl

    - name: Run Python script
      run: |
        #python wencai.py
        python season_report.py
      env:
        KEYWORD: ${{ secrets.KEYWORD }}

    #- name: Run Custom data script
    #  run: |
    #    python popularity.py
      
    - name: Commit changes
      run: |
        git add .
        git commit --allow-empty -m "spider"
        git push
